# Generated by Django 5.2.7 on 2025-10-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
