# Generated by Django 5.2.5 on 2025-10-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='trainer.trainer'),
        ),
    ]
