# Generated by Django 5.2.7 on 2025-10-06 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_phone_number'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.trainer'),
        ),
    ]
