# Generated by Django 5.2.6 on 2025-10-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_created_at_member_height_member_trainer_and_more'),
        ('member', '0002_member_phone_number'),
    ]

    operations = [
    ]
