# Generated by Django 5.2.7 on 2025-10-03 08:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='trainer.trainer'),
        ),
        migrations.AddField(
            model_name='diet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 3, 13, 39, 53, 956139)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='member.member'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets', to='member.member'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diets', to='trainer.trainer'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='member.member'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='trainer.trainer'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'date')},
        ),
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmis', to='member.member')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bmis', to='trainer.trainer')),
            ],
        ),
    ]
